<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Fadillah Juliashar">
<meta name="dcterms.date" content="2024-01-09">

<title>PENGARUH EKSPOR DAN IMPOR BATU BARA TERHADAP PDB INDONESIA TAHUN 2013-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PENGARUH EKSPOR DAN IMPOR BATU BARA TERHADAP PDB INDONESIA TAHUN 2013-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Fadillah Juliashar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 9, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="LOGO%20APP.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><strong>POLITEKNIK APP JAKARTA</strong></figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Peran penting batu bara sebagai sumber daya energi menimbulkan dampak besar pada perekonomian Indonesia, terutama melalui ekspor dan impor batu bara yang saling terkait dengan Pertumbuhan Domestik Bruto (PDB). Indonesia telah menjadi aktor kunci dalam pasar global batu bara dari tahun 2013 hingga 2022 (Leonard, 2019). PDB Indonesia sangat terkait dengan sektor energi, di mana kontribusi batu bara menjadi faktor signifikan.</p>
<p>Ekspor batu bara memiliki pengaruh langsung terhadap penerimaan devisa negara, sementara impor mencerminkan kebutuhan energi dalam negeri dan kebijakan pemerintah terkait. Dalam kurun waktu 2013-2022, fluktuasi harga batu bara di pasar internasional turut menentukan dampak ekspor dan impor terhadap PDB. Kondisi ini tercermin dalam kebijakan pemerintah seputar pengelolaan sumber daya alam, dinamika harga global, dan perubahan dalam struktur ekonomi serta industri.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang Lingkup</h3>
<p>Objek penelitian ini dibatasi hanya di negara Indonesia dan tidak meluas ke zona negara tertentu. Variable yang akan digunakan pada analisis kali ini yaitu nilai ekspor, nilai impor dan nilai PDB Indonesia.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan Masalah</h3>
<p>Rumusan masalah dari penelitian ini adalah:</p>
<p>• Apakah ada pengaruh ekspor batu bara terhadap PDB Indonesia?</p>
<p>• Apakah ada pengaruh impor batu bara terhadap PDB Indonesia?</p>
<p>• Berapa besar pengaruh ekspor dan impor batu bara terhadap PDB Indonesia?</p>
</section>
<section id="tujuan-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-penelitian"><span class="header-section-number">1.4</span> Tujuan Penelitian</h3>
<p>Tujuan penelitian ini adalah untuk mengetahui apakah ada pengaruh ekspor dan impor batu bara terhadap PDB Indonesia serta berapa besar pengaruhnya.</p>
</section>
<section id="manfaat-penelitian" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="manfaat-penelitian"><span class="header-section-number">1.5</span> Manfaat Penelitian</h3>
<p>Manfaat teoritisnya antara lain adalah untuk memberikan wawasan baru bagi kalangan akademisi seputar topik ini. Sementara itu, manfaat praktisnya adalah memberikan uraian mendalam mengenai bagaimana melakukan analisis regresi di R studio serta dapat memberikan input bagi policy maker untuk mengatur ekspor impor batu bara agar dapat meningkatkan PDB jika terdapat pengaruh.</p>
</section>
<section id="package" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="package"><span class="header-section-number">1.6</span> Package</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi Pustaka</h2>
<section id="ekspor-batu-bara" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="ekspor-batu-bara"><span class="header-section-number">2.1</span> Ekspor Batu Bara</h3>
<p>Ekspor batu bara Indonesia menjadi salah satu pilar utama pendapatan devisa negara. Menurut data dari Badan Pusat Statistik (2022). Setelah mencapai puncaknya pada tahun 2019, ekspor batu bara Indonesia mengalami fluktuasi yang mencerminkan berbagai faktor dalam dinamika pasar global.</p>
<p>Beberapa faktor kunci yang mempengaruhi ekspor batu bara adalah:</p>
<p>• Permintaan Global dan Harga Batu Bara : Permintaan global terhadap batu bara memiliki dampak signifikan terhadap kinerja ekspor Indonesia. Analisis oleh International Energy Agency (IEA) dan International Monetary Fund (IMF) menyoroti peran tumbuhnya ekonomi global khususnya di Asia dalam meningkatkan permintaan energi, termasuk batu bara. Selain itu, fluktuasi harga batu bara dunia yang tercermin dalam Indeks Harga Batu Bara Newcastle juga menjadi faktor yang signifikan (World Bank, 2022).</p>
<p>• Kebijakan Perdagangan dan Regulasi : Kebijakan perdagangan dan regulasi baik di tingkat nasional maupun internasional memainkan peran penting. Undang-Undang Minerba dan kebijakan ekspor mineral Indonesia bersama dengan perubahan kebijakan di negara mitra dagang dapat menciptakan perubahan dalam volume dan nilai ekspor batu bara (Kementerian Energi dan Sumber Daya Mineral, 2022).</p>
<p>• Infrastruktur dan Logistik : Infrastruktur dan kelancaran logistik juga memengaruhi kapasitas ekspor batu bara. Pembangunan dan perbaikan infrastruktur pelabuhan serta jaringan transportasi menjadi faktor kunci yang disoroti dalam literatur (Purwanto, 2016).</p>
<p>• Dampak Pandemi dan Transisi Energi : Pandemi COVID-19 dan tren menuju energi bersih memberikan konteks penting. Analisis dampak pandemi terhadap permintaan energi dan perdagangan global bersama dengan transisi menuju energi bersih, memperumit dinamika ekspor batu bara (IEA, 2022).</p>
</section>
<section id="impor-batu-bara" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="impor-batu-bara"><span class="header-section-number">2.2</span> Impor Batu Bara</h3>
<p>Selain ekspor, impor batu bara juga menjadi faktor penting yang memengaruhi keseimbangan perdagangan Indonesia. Penting untuk dicatat bahwa impor batu bara memiliki peran strategis dalam menjaga kestabilan pasokan domestik Indonesia. Meskipun Indonesia adalah eksportir batu bara terbesar, fluktuasi dalam produksi dan permintaan domestik dapat menimbulkan ketidakseimbangan pasokan.</p>
<p>Data dari Badan Pusat Statistik (2022) menunjukkan variasi impor batu bara selama periode 2013-2022, mengindikasikan respons pemerintah terhadap perubahan kondisi pasar. Kebijakan impor batu bara turut memainkan peran kunci dalam menjaga ketahanan energi nasional dan menyediakan pasokan yang memadai bagi sektor industri. Untuk lebih memahami dampaknya terhadap PDB Indonesia, perlu diperhatikan pula peran impor batu bara dalam mencapai target kebutuhan energi dalam negeri.</p>
</section>
<section id="pdb-indonesia" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="pdb-indonesia"><span class="header-section-number">2.3</span> PDB Indonesia</h3>
<p>Pertumbuhan ekonomi diukur melalui Produk Domestik Bruto (PDB). PDB mencakup total nilai semua barang dan jasa yang dihasilkan dalam batas wilayah suatu negara selama periode tertentu (Wulandari, 2021). Selain sebagai indikator utama pertumbuhan ekonomi PDB juga memberikan informasi penting tentang struktur sektor ekonomi, distribusi pendapatan, dan daya beli masyarakat.</p>
<p>Dalam konteks Indonesia, PDB menjadi cermin keberhasilan kebijakan ekonomi dan perkembangan sektor-sektor kunci seperti pertanian, industri, dan jasa. Pertumbuhan PDB yang stabil dapat mencerminkan keberlanjutan pembangunan ekonomi, sementara fluktuasi dalam pertumbuhan PDB dapat menjadi sinyal terhadap tantangan dan peluang yang dihadapi negara. PDB per kapita yang merupakan PDB dibagi dengan jumlah penduduk, memberikan gambaran tentang distribusi pendapatan dan standar hidup masyarakat. Selain itu, sektor-sektor kontributor terhadap PDB, seperti manufaktur, pertambangan, dan sektor jasa, juga memberikan wawasan tentang struktur ekonomi suatu negara.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode Penelitian</h2>
<p>Berikut adalah data yang digunakan sebagai objek penelitian, data dibawah ini merupakan data nilai Ekspor-Impor dan Nilai PDB Indonesia.</p>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">TAHUN</th>
<th style="text-align: center;"><p>EXPORT (X1)</p>
<p>(Tons)</p></th>
<th style="text-align: center;"><p>IMPORT (X2)</p>
<p>(Tons)</p></th>
<th style="text-align: center;"><p>PDB Indonesia (Y)</p>
<p>(Milyaran Rupiah)</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">381,519,674</td>
<td style="text-align: center;">510,864</td>
<td style="text-align: center;">9,546,134</td>
</tr>
<tr class="even">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">356,302,906</td>
<td style="text-align: center;">2,274,907</td>
<td style="text-align: center;">10,569,705,3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">327,181,897</td>
<td style="text-align: center;">2,815,325</td>
<td style="text-align: center;">11,526,332,8</td>
</tr>
<tr class="even">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">310,662,259</td>
<td style="text-align: center;">3,565,029</td>
<td style="text-align: center;">12,401,728,5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">319,098,477</td>
<td style="text-align: center;">4,352,351</td>
<td style="text-align: center;">13,589,825,7</td>
</tr>
<tr class="even">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">343,124,011</td>
<td style="text-align: center;">5,357,791</td>
<td style="text-align: center;">14,838,756</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">374,935,870</td>
<td style="text-align: center;">6,769,368</td>
<td style="text-align: center;">15,832,657,2</td>
</tr>
<tr class="even">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">341,547,629</td>
<td style="text-align: center;">7,955,444</td>
<td style="text-align: center;">15,443,353,2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">345,453,158</td>
<td style="text-align: center;">13,437,545</td>
<td style="text-align: center;">16,976,690,8</td>
</tr>
<tr class="even">
<td style="text-align: center;">2022</td>
<td style="text-align: center;">360,285,221</td>
<td style="text-align: center;">10,699,219</td>
<td style="text-align: center;">19,588,445,6</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data <em>Time Series</em> tahun 2013-2022. Data yang ada diperoleh dari Trademap dan Badan Pusat Statistik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>METOPEN <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">'FADILLAH JULIASHAR UAS.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode Analisis</h3>
<p>Penelitian ini menggunakan Teknik Analisis Kuantitatif Deskriptif dengan metode Regresi Multivariat. Dua variabel independen yang dipilih adalah Ekspor dan Impor, sedangkan variabel dependennya adalah Produk Domestik Bruto. Tujuan utama penelitian ini adalah untuk mengeksplorasi dan mengidentifikasi hubungan antara Ekspor (X1) dan Impor (X2) dengan PDB Indonesia (Y). Spesifikasi yang dilakukan adalah :</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x1+\beta_2 x2+\mu
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah PDB, <span class="math inline">\(x1\)</span> adalah Export dan <span class="math inline">\(x2\)</span> adalah Import</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan Masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">Std. Error</th>
<th style="text-align: center;">t- Value</th>
<th style="text-align: center;">Prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Intecerpt</td>
<td style="text-align: center;">8.663E+06</td>
<td style="text-align: center;">7.324E+06</td>
<td style="text-align: center;">1.183</td>
<td style="text-align: center;">0.27550</td>
</tr>
<tr class="even">
<td style="text-align: center;">X1</td>
<td style="text-align: center;">3.772E-03</td>
<td style="text-align: center;">2.111E-02</td>
<td style="text-align: center;">0.179</td>
<td style="text-align: center;">0.86326</td>
</tr>
<tr class="odd">
<td style="text-align: center;">X2</td>
<td style="text-align: center;">7.038E-01</td>
<td style="text-align: center;">1.212E-01</td>
<td style="text-align: center;">5.805</td>
<td style="text-align: center;">0.00066</td>
</tr>
<tr class="even">
<td style="text-align: center;">R squared</td>
<td style="text-align: center;">0.8288</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Adjusted R-Squared</td>
<td style="text-align: center;">0.7799</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">F-Statistic</td>
<td style="text-align: center;">16.94</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Prob (F-Statistic)</td>
<td style="text-align: center;">0.002077</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Persamaan regresinya adalah</p>
<p><strong>Y = 8.663 + 3.772x1 + 7.038x2</strong></p>
<p>Ekspor batu bara memiliki nilai koefisien yang positif, yang berarti semakin meningkat ekspor, semakin tinggi PDB. Namun, ekspor batu bara tidak berpengaruh signifikan terhadap PDB, p = 0.86326. Impor batu bara memiliki koefisien yang positif pula, yang berarti semakin meningkat impor, semakin tinggi PDB. Walaupun demikian, impor batu bara tidak berpengaruh signifikan terhadap PDB, p = 0.00066</p>
<p>Nilai adjusted R-squared sebesar 0.7799 berarti 77,99% variasi pada PDB dapat dijelaskan oleh kedua variabel independent. Nilai probabilitas F statistik yang lebih kecil 0.05 (p = 0.002077) berarti secara bersama-sama ekspor dan impor batu bara berpengaruh signifikan terhadap PDB.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis Masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2, <span class="at">data =</span> METOPEN)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2, data = METOPEN)

Residuals:
     Min       1Q   Median       3Q      Max 
-2446193  -774391   -24194   908720  2036797 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 8.663e+06  7.324e+06   1.183  0.27550    
X1          3.772e-03  2.111e-02   0.179  0.86326    
X2          7.038e-01  1.212e-01   5.805  0.00066 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1456000 on 7 degrees of freedom
Multiple R-squared:  0.8288,    Adjusted R-squared:  0.7799 
F-statistic: 16.94 on 2 and 7 DF,  p-value: 0.002077</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>METOPEN<span class="sc">$</span>e <span class="ot">&lt;-</span> <span class="fu">resid</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Setiap kenaikan nilai ekspor batu bara sebesar 1 akan berdampak pada meningkatnya PDB sebesar 3.772 dengan Y yang sama. Sementara itu, setiap kenaikan nilai impor batu bara sebesar 1 akan berdampak pada naiknya PDB sebesar 7.038</p>
<p><em>Plot pengaruh error terhadap nilai Ekspor</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2, <span class="at">data =</span> METOPEN)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(METOPEN<span class="sc">$</span>X1,METOPEN<span class="sc">$</span>e,<span class="at">xlab=</span><span class="st">'Nilai Ekspor'</span>,<span class="at">ylab=</span><span class="st">'error'</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Plot pengaruh error terhadap nilai PDB</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(METOPEN<span class="sc">$</span>X2,METOPEN<span class="sc">$</span>e,<span class="at">xlab=</span><span class="st">"Nilai PDB"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Ekspor dan Impor Batu Bara mempunyai peranan penting dalam memberikan kontribusinya terhadap produk domestik bruto (PDB) Indonesia. Berdasarkan hasil analisis diatas bahwa ekspor maupun impor batu bara tidak mempunyai dampak signifikan terhadap PDB.</p>
<p>Namun jika angka Ekspor dan Impor diakumulasikan kita dapat melihat bahwa kombinasi kedua faktor ini sebenarnya mempunyai dampak yang signifikan terhadap PDB Indonesia. Indonesia dapat memanfaatkan keduanya untuk menghasilkan lebih banyak pendapatan dari sektor batu bara.</p>
<p>Berdasarkan data, kontribusi Ekspor dan Impor batubara terhadap PDB mencapai 77,99% yang menunjukkan dominannya peran sektor ini terhadap pertumbuhan ekonomi negara. Oleh karena itu, penting untuk mempertimbangkan kedua aspek ini secara bersamaan dalam analisis ekonomi dan mempertimbangkan dampaknya terhadap pendapatan dan pertumbuhan ekonomi Indonesia.</p>
</section>
<section id="saran" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="saran"><span class="header-section-number">6</span> Saran</h2>
<p>Untuk meningkatkan akurasi dari penelitian ini, sebaiknya untuk terus memperbanyak variabel yang mendukung variabel terkait.</p>
</section>
<section id="referensi" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="referensi"><span class="header-section-number">7</span> Referensi</h2>
<p>Trade Map. (2022). Statistik Ekspor Impor Batu Bara. https://m.trademap.org/</p>
<p>Badan Pusat Statistik. (2022). Statistik PDB Indonesia. https://www.bps.go.id/</p>
<p>International Energy Agency. (2022). Coal 2022 – Analysis and Forecasts to 2027. https://www.iea.org/</p>
<p>International Monetary Fund. (2022). World Economic Outlook Database. https://www.imf.org/</p>
<p>Kementerian Energi dan Sumber Daya Mineral. (2022). Peraturan Perundang-undangan Sektor Energi dan Sumber Daya Mineral. https://www.esdm.go.id/</p>
<p>Leonard, L. (2019). Indonesia Rajai Pasar Ekspor Batu Bara. Bisnis.com. https://ekonomi.bisnis.com/read/20190527/44/927982/indonesia-rajai-pasar-ekspor-batu-bara</p>
<p>Purwanto, Y. (2016). Analisis Pengaruh Infrastruktur Terhadap Pertumbuhan Ekspor Batubara Indonesia. Jurnal Ilmu Manajemen Dan Akuntansi Terapan, 7(2), 89–104.</p>
<p>World Bank. (2022). Commodities at a Glance: Coal. https://databank.worldbank.org/</p>
<p>Wulandari, T. (2021). Pendapatan Nasional: Pengertian dan Jenisnya. Detik. https://www.detik.com/edu/detikpedia/d-5817378/pendapatan-nasional-pengertian-dan-jenisnya</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>